version: '3.3'
services:
  api:
    build: "."
    ports:
      - "80"
    restart: "always"
    networks:
      - "api.network"
    deploy:
      replicas: 5
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - api
    ports:
      - "8080:80"
    networks: 
      - "api.network"
networks: 
  api.network: